[observatory]
observatory_lat = -29.0182
observatory lon = -70.6915

[instrument]
primary_diam = 6.5
secondary_diam = 0.23

pixel_scale = .008
rotation = 0.0
NORTH_clio = -1.797

#Wrong, used to convert values into real numbers
zero_pt_flux_HA = 0.0 
zero_pt_flux_CONT = 0.0 

cen_wave_HA = 0.6564
cen_wave_CONT = 0.643
# Need to find the right value
cen_wave_J = 1.2 
cen_wave_H = 1.63465
cen_wave_Ks = 2.1167
cen_wave_3.1 = 3.1
cen_wave_3.3 = 3.3
cen_wave_Lp = 3.7581
cen_wave_3.9 = 3.9
cen_wave_Mp = 4.76855

#Clio
clio_fpm_diam_HA = 0.0 
clio_fpm_diam_CONT = 0.0 

#VisAO
fpm_diam_HA = 0.0 
fpm_diam_CONT = 0.0 
