# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI tests

on:
  workflow_dispatch:
  push:
    branches: 
      - '*' # run on all
  pull_request:
    branches: 
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install pytest 
        pip install -r requirements.txt .
    - name: Test with pytest
      run: |
        pytest --cov
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
